### ISSUE TITLE
USER STORY : Project Installation

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#11]
**EPIC:** #2 

As a **Developer** I can **Setup my workspace in Gitpod and install Django** so that **I can have a stable base to work with**

**Acceptance Criteria**
- Create a new dashboard in Gitpod using the provided template and install Django
- Be able to run the base template without any issues

**Tasks:**

- [x] Task1: Open a new dashboard in Gitpod using the project repository
- [x] Task2: Install Django and setting up baseline files
- [x] Task3: Make sure the base app can be run in devview

**Comment by Oile995** [comment]
Setup new django project with base requirements added.
![deployed](https://github.com/Oile995/Project5/assets/11351866/9e7b0e5c-101e-452d-83eb-7a51ba8207a9)
