### ISSUE TITLE
USER STORY : Create Account

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#12]
**EPIC:** #3 

As a **site user** I can **create an account** so that **pay and access all features necessary**

**Acceptance Criteria**
- As a new site user you should be directed to creating a new account or log in when trying to access gatekept content
- It should be easy to access login/Registration page
- Email confirmation is required when creating a new account

**Tasks:**
- [x] Task1: Setup Allauth in Django project
- [x] Task2: Download Allauth templates
- [x] Task3: Create a Profile model
- [x] Task4: Modify applicable Allauth templates
- [x] Task5: Add Authentication restrictions where applicable
- [x] Task6: Test the following features that they are implemented correctly: Create account, log-in/out features and Authentication where needed.

**Comment by Oile995** [comment]
Setup allauth in project inception with templates.
Created profile app and model.
Modified allauth templates to show with applicable information.
Added authentication restrictions where needed.


![Image](https://github.com/Oile995/Project5/assets/11351866/1d41eb3a-515d-4459-b079-d95af8a48d8c)
