### ISSUE TITLE
USER STORY : Site admin

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#14]
**EPIC:** #3 

As a **Site admin** I can **access the site as superuser** so that ** I can Add, update or delete products and deals.**

**Acceptance Criteria**
- You should be able to log into the site as a superuser and have the option to add, update or delete product and deals
- Monitor product status

**Tasks:**

- [x] Task1: Add a superuser to the Django app
- [x] Task2: Add admin views applicable to products, deals and categories in admin panel
- [x] Task3: Test that admin can fully maintain the website using the admin panel as intended

**Comment by Oile995** [comment]
Added superuser and admin views for the different models
Can add update and remove categories subcategories and products from admin page

![Image](https://github.com/Oile995/Project5/assets/11351866/64f38f87-a65e-4fb6-a2d0-8a4771bcb0dc)
