### ISSUE TITLE
USER STORY : Navigation Bar

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#15]
**EPIC:** #4 
As a **Site User** I can **access all features, categories and links from a detailed navigation bar** so that **I can quickly and easily navigate the website with minimum amount of input**

**Acceptance Criteria**
- The navigation bar must always be visible or easily accessed
- Status of authentication and shopping cart must be shown
- Dropdown option for navigation to different categories  

**Tasks:**
- [x] Task1: Add a sleek but functional navigation bar with many dropdown options depending on category
- [x] Task2: Add shopping cart icon with dropdown for details
- [x] Task3: Add authentication responsive Register/login/out anchor
- [x] Task4:  Test responsiveness of navbar and that all links are working

**Comment by Oile995** [comment]
Added responsive navbar with dropdowns, both for mobile and desktop.
Need to update links once other pages have been made.
