### ISSUE TITLE
USER STORY : Detailed product view

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#16]
**EPIC:** #4 

As a **site user ** I can **access a detailed view of the product I have selected** so that **I can read the details and decide if I want to add it to the shopping cart**

**Acceptance Criteria**
- Once a product has been clicked, a detailed view for said product will be displayed.
- In the detailed view a picture of the product, Name & description, review and specification is displayed in a clear fashion
- Other products in the same category will be displayed beneath in a paginated way

**Tasks:**

- [x] Task1: Create template and view for detailed product
- [x] Task2: Customize CSS and HTML to fit the Wireframe for the detailed view
- [x] Task3: Add paginated list model for other products in the same category and it below the product view
- [x] Task4: Test that all data is reflecting the product and that the paginated list is working

**Comment by Oile995** [comment]
Started view and template for detailed product

**Comment by Oile995** [comment]
Customized Details page more to have the same layout as wireframe, need categories to be worked on in view for correct query

**Comment by Oile995** [comment]
Finished layout for all elements in product details page, need to tweak pagination, add video option in right column and add comment/rating.
Then add applicable css for style

![Image](https://github.com/Oile995/Project5/assets/11351866/bf44b29e-5148-41c3-b52a-747539f62266)
