### ISSUE TITLE
USER STORY : Display products list 

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#17]
**EPIC:** #4 

As a **Site user** I can **view and scroll through the products in a card based fashion** so that I can **get a quick and clear overview of the products when looking for my next purchase**

**Acceptance Criteria**
- I want the product overview to be modern, classy and easy to navigate
- I want to get information about the name, price and review of the product
- I want a clear picture of each product separately
- I want sufficient amounts of products per row, responsive to the device

**Tasks:**

- [x] Task1: Create models for product
- [x] Task2: Create view template for products with and without dependency of category
- [x] Task3: Style template so that size of product card is displayed according to acceptance criteria
- [x] Task4: Test that implemented functionality is working as intended

**Comment by Oile995** [comment]
Added product list view with responsive cards depending on site width. Will need to do some tweaking for odd lower sizes

![Image](https://github.com/Oile995/Project5/assets/11351866/652ae161-ba6e-4cb3-a2b8-221cfdf08538)
