### ISSUE TITLE
USER STORY : Cart dropdown

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#18]
**EPIC:** #4 

As a **shopper** I can **click the shopping cart in the navigation-bar at any time** so that **I can view the current products and amount**

**Acceptance Criteria**
- A number for amount of products added into the cart should always be visible
- Once clicked a dropdown will show product in the cart and total amount, as well as a link to checkout

**Tasks:**

- [x] Task1: Add Shopping cart icon with dropdown logic in navigation bar
- [x] Task2: Add Shopping cart app with context
- [x] Task3: Test functionality and that it is working as intended

**Comment by Oile995** [comment]
Added cart and cart dropdown menu with products displayed in the cart.
![cart](https://github.com/Oile995/Project5/assets/11351866/c1015b31-4867-4a20-8ebf-1f1e0e581492)
