### ISSUE TITLE
USER STORY : Scrolling Hero banner

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#19]
**EPIC:** #4 

As a **Site User** I can **view scrolling hero banner with clickable links on the home page with announcements** so that I can **review current highlights, announcements and be able to access their product details page **

**Acceptance Criteria**
- As a site user I want a modern, eye-catching and informational scrolling hero banner
- As a site user I want the scrolling hero banner to give me information about any discounts, seasonal offers, new arrivals etc.
- I want the scrolling hero banner to only be visible on the homepage

**Tasks:**

- [x] Task1: Add global tag in product model
- [x] Task2: Add self-scrolling slideshow as hero-image on index page
- [x] Task3: Test that implemented functionality is working as intended

**Comment by Oile995** [comment]
Index page carousel has been added but with specific pictures at the moment.

**Comment by Oile995** [comment]
Created a carousel and updated with text and pictures and a slide inside for loop, for products that should be displayed.

![Image](https://github.com/Oile995/Project5/assets/11351866/99ed2108-496a-4372-a5ac-466b0b643a02)
