### ISSUE TITLE
USER STORY : Deals banner

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#20]
**EPIC:** #4 

As a **Site User** I can **see a deal banner below the navigation bar highlighting current deals** so that I can **quickly and easily see current deals from the home page**

**Acceptance Criteria**
- As a site user I want the deals banner to be on top of the scrolling hero banner
- I want the deals banner to be monochromatic and different color from the scrolling hero banner
- I want the site banner to be eye-catching and informational of any new deals, discounts and offers with a clear and simple text informing me about that

**Tasks:**
- [x] Task1: Create model for alert deals
- [x] Task2: Style and add alert to base template
- [x] Task3: Test that deal banner can be edited by admin and is showing as intended.

**Comment by Oile995** [comment]
Created a deal banner that are showing the limit until free deliver.

![Image](https://github.com/Oile995/Project5/assets/11351866/5e3bbe3d-2dd1-4e45-b8be-e3cd0bf9fb27)
