### ISSUE TITLE
USER STORY : Search function in Navbar

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#21]
**EPIC:** #5 

As a **Site User** I can **always access the search function in the navigation bar** so that I can **always search for the specific product**

**Acceptance Criteria**
- As I site user I want a clear and visible search bar
- I want the search bar to have a little magnifying tool icon on it
- When searched I want the product list view to show all applicable products

**Tasks:**

- [x] Task1: Add search form and icon in nav-bar
- [x] Task2: Add search logic in product list view
- [x] Task3: Test that implemented function is working as intended

**Comment by Oile995** [comment]
Added search function to navbar and tested that product will show from either name or details.
Light tweaking for further search options in the future
