### ISSUE TITLE
USER STORY : Sorting card option

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#22]
**EPIC:** #5 

As a **site user** I can **sort the product cards per name or price** so that **quickly find the cheapest/most expensive product or by the name quickly**

**Acceptance Criteria**
- When in product list view, I should be able to click a sorting button that gives the dropdown toggle option of price or alphabet
- When clicking these the sorting of products will be toggling from lowest to highest or First to last letter in the alphabet 

**Tasks:**

- [x] Task1: Add sorting logic to the product list view and templates
- [x] Task2: Add togglable button for price and alphabet at the top of product list view
- [x] Task3: Test functionality is implemented as intended

**Comment by Oile995** [comment]
Added sorting logic and option for product view

![Image](https://github.com/Oile995/Project5/assets/11351866/0c5ce8ce-1da4-4d21-82db-07de8c9a8ec4)
