### ISSUE TITLE
USER STORY : Category selection

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#23]
**EPIC:** #5 

As a **site user** I can **access products under certain categories** so that **narrow down my search for my product under the correct category**

**Acceptance Criteria**
- I should at any point be able to select category from a drop-down option in the navigation bar
- When clicking these the product list view will only show all products under this category

**Tasks:**

- [x] Task1: Create category model
- [x] Task2: Add category logic in both product list view and template
- [x] Task3: Test functionality is implemented as intended

**Comment by Oile995** [comment]
Added Category selection If in Product views and template to implement functional category selection.
Need more categories to finish all links
