### ISSUE TITLE
USER STORY : Payment service

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#24]
**EPIC:** #6 

As a **site user** I can **Easy and safely pay for my shopping cart** so that I can **be sure that my payments are secure and will go through when paying**

**Acceptance Criteria**
- When checking out the shopping cart, I should be able to get an order for all products in the cart and pay for the total

**Tasks:**
- [x] Task1: Create checkout models and templates
- [x] Task2: Create a Stripe account and install it in the Django project 
- [x] Task3: Add error catching when filling out the form and the payment method
- [x] Task4: Test functionality and implementation is made as intended

**Comment by Oile995** [comment]
Added stripe and error catching for both card and form.
Added webhooks.
Added order details saving form to both user and through webhooks.


![Image](https://github.com/Oile995/Project5/assets/11351866/dea1d2ea-1b71-41c1-a840-c98ebf67e525)
