### ISSUE TITLE
USER STORY : Add products

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#26]
**EPIC:** #8 

As a **Site admin** I can **add products in frontend** so that I can **add new products without accessing the admin panel**

**Acceptance Criteria**
- Without accessing the admin page, a superuser should have the option to add new products

**Tasks:**

- [x] Task1: Add front end form for adding new products to the page
- [x] Task2: Style the form to fit the wireframes
- [x] Task3: Test that the form is working as intended

**Comment by Oile995** [comment]
Added the functions to create new Categories, Subcategories and Products.

![Image](https://github.com/Oile995/Project5/assets/11351866/d44c3eda-cb15-49b6-bd2e-3fb90f827b25)
