### ISSUE TITLE
USER STORY : Update products

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#27]
**EPIC:** #8 

As a **Site admin** I can **update products in frontend** so that I can **update products without accessing the admin panel**

**Acceptance Criteria**
- Without accessing the admin page, a superuser should have the option to update current products

**Tasks:**

- [x] Task1: Add front end form in product details view for updating
- [x] Task2: Style the html form to fit the wireframes
- [x] Task3: Test that the update is working as intended

**Comment by Oile995** [comment]
Added front end form for superuser to edit products.


![Image](https://github.com/Oile995/Project5/assets/11351866/8b2150e9-4d7c-4b7a-aaf6-c25ab0136a5b)
