### ISSUE TITLE
USER STORY : Delete products

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#28]
**EPIC:** #8 

As a **Site admin** I can **delete products in frontend** so that I can **delete products without accessing the admin panel**

**Acceptance Criteria**
- Without accessing the admin page, a superuser should have the option to delete current products

**Tasks:**

- [x] Task1: Add delete product button to product details
- [x] Task2: Add bootstrap modal for confirmation
- [x] Task3: Test that the deletion is working as intended

**Comment by Oile995** [comment]
Created delete function and added modal for popup confirmation before deleting.

![Image](https://github.com/Oile995/Project5/assets/11351866/c471ea80-d0b5-4b10-81bc-d47bb9d286b4)
