### ISSUE TITLE
USER STORY : Add Reviews/Comments

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#29]
**EPIC:** #8 

As a **Site User** I can **add my reviews/comments to a product** so that I can **share my thoughts on the product to other shoppers**

**Acceptance Criteria**
- In product details, a authenticated customer should be able to add a review/comment to said product

**Tasks:**

- [x] Task1: Add model for reviews
- [x] Task2: Add authenticate-gated front end form to add a new review in product details
- [x] Task3: Test that the implemented features are working as intended

**Comment by Oile995** [comment]
Added and modified my Review model and created a form/view for it.
Got star rating functions, html and css from :https://github.com/dev-rathankumar/greatkart-pre-deploy/blob/main/store/models.py
Tested both as super user, not logged and test user and everything is working as intended!


![Image](https://github.com/Oile995/Project5/assets/11351866/efa6021a-b94a-47df-b51b-96a95066143d)
