### ISSUE TITLE
USER STORY: Wireframes

### ISSUE THREAD

**Issue by Oile995** [Oile995/Project5#9]
**EPIC:** #2 

As a **Developer** I can **draw easy but clear wireframes using Whimsical** so that **visualize the final product and use as a template when coding and styling**

**Acceptance Criteria**
- This user story is completed once all wireframes for the site is completed.
- The wireframes must be clear with navbar, image placeholders and product card structure
- At least 1-2 wireframes of mobile devices to show how the site is displayed on smaller screens.

**Tasks:**

- [x] Task1: Create a homepage
- [x] Task2: Create a product display page
- [x] Task3: Create a product details page
- [x] Task4: Create a shopping cart/payment view

**Comment by Oile995** [comment]
Finished wireframes for project
